<img src="http://www.digitalvidya.com/wp-content/uploads/2013/05/logoa5-300x95.png">

## Data Analysis using Python Assignment
### Digital Vidya Copyright

#### Download the IPL dataset from the given link and load it in a dataframe using the following command.
#### This dataset contains details of each match played in IPL from season 2008 to 2016. Each row represents one match.
#### Answer the questions based on the dataset. 
#### Please show the code you would use to get to the answer.

In [1]:
import pandas as pd
import numpy as np

In [136]:
matches = pd.read_csv(r'C:\Users\balajkm\Desktop\practise\data set\IPL dataset\matches.csv') 
matches

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2008,Bangalore,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,NaN
1,2,2008,Chandigarh,2008-04-19,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Chennai Super Kings,33,0,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",MR Benson,SL Shastri,NaN
2,3,2008,Delhi,2008-04-19,Rajasthan Royals,Delhi Daredevils,Rajasthan Royals,bat,normal,0,Delhi Daredevils,0,9,MF Maharoof,Feroz Shah Kotla,Aleem Dar,GA Pratapkumar,NaN
3,4,2008,Mumbai,2008-04-20,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,normal,0,Royal Challengers Bangalore,0,5,MV Boucher,Wankhede Stadium,SJ Davis,DJ Harper,NaN
4,5,2008,Kolkata,2008-04-20,Deccan Chargers,Kolkata Knight Riders,Deccan Chargers,bat,normal,0,Kolkata Knight Riders,0,5,DJ Hussey,Eden Gardens,BF Bowden,K Hariharan,NaN
5,6,2008,Jaipur,2008-04-21,Kings XI Punjab,Rajasthan Royals,Kings XI Punjab,bat,normal,0,Rajasthan Royals,0,6,SR Watson,Sawai Mansingh Stadium,Aleem Dar,RB Tiffin,NaN
6,7,2008,Hyderabad,2008-04-22,Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,normal,0,Delhi Daredevils,0,9,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",IL Howell,AM Saheba,NaN
7,8,2008,Chennai,2008-04-23,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,normal,0,Chennai Super Kings,6,0,ML Hayden,"MA Chidambaram Stadium, Chepauk",DJ Harper,GA Pratapkumar,NaN
8,9,2008,Hyderabad,2008-04-24,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,3,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,MR Benson,NaN
9,10,2008,Chandigarh,2008-04-25,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Kings XI Punjab,66,0,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",Aleem Dar,AM Saheba,NaN
10,11,2008,Bangalore,2008-04-26,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,7,SR Watson,M Chinnaswamy Stadium,MR Benson,IL Howell,NaN
11,12,2008,Chennai,2008-04-26,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,bat,normal,0,Chennai Super Kings,0,9,JDP Oram,"MA Chidambaram Stadium, Chepauk",BF Bowden,AV Jayaprakash,NaN
12,13,2008,Mumbai,2008-04-27,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,normal,0,Deccan Chargers,0,10,AC Gilchrist,Dr DY Patil Sports Academy,Asad Rauf,SL Shastri,NaN
13,14,2008,Chandigarh,2008-04-27,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,normal,0,Kings XI Punjab,0,4,SM Katich,"Punjab Cricket Association Stadium, Mohali",RE Koertzen,I Shivram,NaN
14,15,2008,Bangalore,2008-04-28,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,bat,normal,0,Chennai Super Kings,13,0,MS Dhoni,M Chinnaswamy Stadium,BR Doctrove,RB Tiffin,NaN
15,16,2008,Kolkata,2008-04-29,Kolkata Knight Riders,Mumbai Indians,Kolkata Knight Riders,bat,normal,0,Mumbai Indians,0,7,ST Jayasuriya,Eden Gardens,BF Bowden,AV Jayaprakash,NaN
16,17,2008,Delhi,2008-04-30,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Delhi Daredevils,10,0,GD McGrath,Feroz Shah Kotla,Aleem Dar,I Shivram,NaN
17,18,2008,Hyderabad,2008-05-01,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,7,SE Marsh,"Rajiv Gandhi International Stadium, Uppal",BR Doctrove,RB Tiffin,NaN
18,19,2008,Jaipur,2008-05-01,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,bat,normal,0,Rajasthan Royals,45,0,SA Asnodkar,Sawai Mansingh Stadium,RE Koertzen,GA Pratapkumar,NaN
19,20,2008,Chennai,2008-05-02,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,bat,normal,0,Delhi Daredevils,0,8,V Sehwag,"MA Chidambaram Stadium, Chepauk",BF Bowden,K Hariharan,NaN
20,21,2008,Hyderabad,2008-05-25,Deccan Chargers,Royal Challengers Bangalore,Deccan Chargers,bat,normal,0,Royal Challengers Bangalore,0,5,R Vinay Kumar,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,RE Koertzen,NaN
21,22,2008,Chandigarh,2008-05-03,Kings XI Punjab,Kolkata Knight Riders,Kings XI Punjab,bat,normal,0,Kings XI Punjab,9,0,IK Pathan,"Punjab Cricket Association Stadium, Mohali",DJ Harper,I Shivram,NaN
22,23,2008,Mumbai,2008-05-04,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,29,0,SM Pollock,Dr DY Patil Sports Academy,IL Howell,RE Koertzen,NaN
23,24,2008,Jaipur,2008-05-04,Chennai Super Kings,Rajasthan Royals,Chennai Super Kings,bat,normal,0,Rajasthan Royals,0,8,Sohail Tanvir,Sawai Mansingh Stadium,Asad Rauf,AV Jayaprakash,NaN
24,25,2008,Bangalore,2008-05-05,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,S Sreesanth,M Chinnaswamy Stadium,SJ Davis,BR Doctrove,NaN
25,26,2008,Chennai,2008-05-06,Chennai Super Kings,Deccan Chargers,Deccan Chargers,field,normal,0,Deccan Chargers,0,7,AC Gilchrist,"MA Chidambaram Stadium, Chepauk",MR Benson,RB Tiffin,NaN
26,27,2008,Mumbai,2008-05-07,Rajasthan Royals,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,7,A Nehra,Dr DY Patil Sports Academy,DJ Harper,RE Koertzen,NaN
27,28,2008,Delhi,2008-05-08,Delhi Daredevils,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,4,MS Dhoni,Feroz Shah Kotla,Aleem Dar,RB Tiffin,NaN
28,29,2008,Kolkata,2008-05-08,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,bat,normal,0,Kolkata Knight Riders,5,0,SC Ganguly,Eden Gardens,Asad Rauf,IL Howell,NaN
29,30,2008,Jaipur,2008-05-09,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,8,YK Pathan,Sawai Mansingh Stadium,MR Benson,AM Saheba,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,548,2016,Rajkot,2016-05-03,Gujarat Lions,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,8,RR Pant,Saurashtra Cricket Association Stadium,CB Gaffaney,BNJ Oxenford,NaN
548,549,2016,Kolkata,2016-05-04,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kolkata Knight Riders,7,0,AD Russell,Eden Gardens,AK Chaudhary,HDPK Dharmasena,NaN
549,550,2016,Delhi,2016-05-05,Delhi Daredevils,Rising Pune Supergiants,Rising Pune Supergiants,field,normal,0,Rising Pune Supergiants,0,7,AM Rahane,Feroz Shah Kotla,C Shamshuddin,RJ Tucker,NaN
550,551,2016,Hyderabad,2016-05-06,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,5,B Kumar,"Rajiv Gandhi International Stadium, Uppal",M Erasmus,S Ravi,NaN
551,552,2016,Bangalore,2016-05-07,Rising Pune Supergiants,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,7,V Kohli,M Chinnaswamy Stadium,CB Gaffaney,BNJ Oxenford,NaN
552,553,2016,Chandigarh,2016-05-07,Kings XI Punjab,Delhi Daredevils,Delhi Daredevils,field,normal,0,Kings XI Punjab,9,0,MP Stoinis,"Punjab Cricket Association IS Bindra Stadium, ...",HDPK Dharmasena,CK Nandan,NaN
553,554,2016,Visakhapatnam,2016-05-08,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Sunrisers Hyderabad,85,0,A Nehra,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,S Ravi,C Shamshuddin,NaN
554,555,2016,Kolkata,2016-05-08,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,5,P Kumar,Eden Gardens,M Erasmus,RJ Tucker,NaN
555,556,2016,Chandigarh,2016-05-09,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,0,Royal Challengers Bangalore,1,0,SR Watson,"Punjab Cricket Association IS Bindra Stadium, ...",AK Chaudhary,HDPK Dharmasena,NaN
556,557,2016,Visakhapatnam,2016-05-10,Sunrisers Hyderabad,Rising Pune Supergiants,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,4,0,A Zampa,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,CB Gaffaney,VK Sharma,NaN
557,558,2016,Bangalore,2016-05-11,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,KH Pandya,M Chinnaswamy Stadium,AY Dandekar,C Shamshuddin,NaN
558,559,2016,Hyderabad,2016-05-12,Sunrisers Hyderabad,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,7,CH Morris,"Rajiv Gandhi International Stadium, Uppal",K Bharatan,M Erasmus,NaN
559,560,2016,Visakhapatnam,2016-05-13,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,normal,0,Kings XI Punjab,0,7,MP Stoinis,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,HDPK Dharmasena,CK Nandan,NaN
560,561,2016,Bangalore,2016-05-14,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,normal,0,Royal Challengers Bangalore,144,0,AB de Villiers,M Chinnaswamy Stadium,AY Dandekar,VK Sharma,NaN
561,562,2016,Kolkata,2016-05-14,Rising Pune Supergiants,Kolkata Knight Riders,Rising Pune Supergiants,bat,normal,1,Kolkata Knight Riders,0,8,YK Pathan,Eden Gardens,A Nand Kishore,BNJ Oxenford,NaN
562,563,2016,Chandigarh,2016-05-15,Kings XI Punjab,Sunrisers Hyderabad,Kings XI Punjab,bat,normal,0,Sunrisers Hyderabad,0,7,HM Amla,"Punjab Cricket Association IS Bindra Stadium, ...",KN Ananthapadmanabhan,M Erasmus,NaN
563,564,2016,Visakhapatnam,2016-05-15,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,80,0,KH Pandya,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Nitin Menon,CK Nandan,NaN
564,565,2016,Kolkata,2016-05-16,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,9,V Kohli,Eden Gardens,CB Gaffaney,A Nand Kishore,NaN
565,566,2016,Visakhapatnam,2016-05-17,Delhi Daredevils,Rising Pune Supergiants,Rising Pune Supergiants,field,normal,1,Rising Pune Supergiants,19,0,AB Dinda,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Nitin Menon,C Shamshuddin,NaN
566,567,2016,Bangalore,2016-05-18,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,1,Royal Challengers Bangalore,82,0,V Kohli,M Chinnaswamy Stadium,KN Ananthapadmanabhan,M Erasmus,NaN
567,568,2016,Kanpur,2016-05-19,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,6,DR Smith,Green Park,AK Chaudhary,CK Nandan,NaN
568,569,2016,Raipur,2016-05-20,Sunrisers Hyderabad,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,6,KK Nair,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
569,570,2016,Visakhapatnam,2016-05-21,Kings XI Punjab,Rising Pune Supergiants,Kings XI Punjab,bat,normal,0,Rising Pune Supergiants,0,4,MS Dhoni,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,HDPK Dharmasena,Nitin Menon,NaN
570,571,2016,Kanpur,2016-05-21,Mumbai Indians,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,6,SK Raina,Green Park,AK Chaudhary,CK Nandan,NaN
571,572,2016,Kolkata,2016-05-22,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kolkata Knight Riders,22,0,YK Pathan,Eden Gardens,KN Ananthapadmanabhan,M Erasmus,NaN
572,573,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
573,574,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
574,575,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
575,576,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
576,577,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [11]:
# 1. What is the easiest way to view the details of the last match of the dataset?
matches.tail(n=1)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
576,577,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [40]:
# 2. Create a slice of this dataframe to only show the details from index 517 to 576 and columns id, season, city 
#and date. Print the output.

c=matches[517:567]
c.groupby(['id','season','city','date']).groups

{(518, 2016, 'Mumbai', '2016-04-09'): Int64Index([517], dtype='int64'),
 (519, 2016, 'Kolkata', '2016-04-10'): Int64Index([518], dtype='int64'),
 (520, 2016, 'Chandigarh', '2016-04-11'): Int64Index([519], dtype='int64'),
 (521, 2016, 'Bangalore', '2016-04-12'): Int64Index([520], dtype='int64'),
 (522, 2016, 'Kolkata', '2016-04-13'): Int64Index([521], dtype='int64'),
 (523, 2016, 'Rajkot', '2016-04-14'): Int64Index([522], dtype='int64'),
 (524, 2016, 'Delhi', '2016-04-15'): Int64Index([523], dtype='int64'),
 (525, 2016, 'Hyderabad', '2016-04-16'): Int64Index([524], dtype='int64'),
 (526, 2016, 'Mumbai', '2016-04-16'): Int64Index([525], dtype='int64'),
 (527, 2016, 'Chandigarh', '2016-04-17'): Int64Index([526], dtype='int64'),
 (528, 2016, 'Bangalore', '2016-04-17'): Int64Index([527], dtype='int64'),
 (529, 2016, 'Hyderabad', '2016-04-18'): Int64Index([528], dtype='int64'),
 (530, 2016, 'Chandigarh', '2016-04-19'): Int64Index([529], dtype='int64'),
 (531, 2016, 'Mumbai', '2016-04-20'): Int64Index([530], dtype='int64'),
 (532, 2016, 'Rajkot', '2016-04-21'): Int64Index([531], dtype='int64'),
 (533, 2016, 'Pune', '2016-04-22'): Int64Index([532], dtype='int64'),
 (534, 2016, 'Delhi', '2016-04-23'): Int64Index([533], dtype='int64'),
 (535, 2016, 'Hyderabad', '2016-04-23'): Int64Index([534], dtype='int64'),
 (536, 2016, 'Rajkot', '2016-04-24'): Int64Index([535], dtype='int64'),
 (537, 2016, 'Pune', '2016-04-24'): Int64Index([536], dtype='int64'),
 (538, 2016, 'Chandigarh', '2016-04-25'): Int64Index([537], dtype='int64'),
 (539, 2016, 'Hyderabad', '2016-04-26'): Int64Index([538], dtype='int64'),
 (540, 2016, 'Delhi', '2016-04-27'): Int64Index([539], dtype='int64'),
 (541, 2016, 'Mumbai', '2016-04-28'): Int64Index([540], dtype='int64'),
 (542, 2016, 'Pune', '2016-04-29'): Int64Index([541], dtype='int64'),
 (543, 2016, 'Delhi', '2016-04-30'): Int64Index([542], dtype='int64'),
 (544, 2016, 'Hyderabad', '2016-04-30'): Int64Index([543], dtype='int64'),
 (545, 2016, 'Rajkot', '2016-05-01'): Int64Index([544], dtype='int64'),
 (546, 2016, 'Pune', '2016-05-01'): Int64Index([545], dtype='int64'),
 (547, 2016, 'Bangalore', '2016-05-02'): Int64Index([546], dtype='int64'),
 (548, 2016, 'Rajkot', '2016-05-03'): Int64Index([547], dtype='int64'),
 (549, 2016, 'Kolkata', '2016-05-04'): Int64Index([548], dtype='int64'),
 (550, 2016, 'Delhi', '2016-05-05'): Int64Index([549], dtype='int64'),
 (551, 2016, 'Hyderabad', '2016-05-06'): Int64Index([550], dtype='int64'),
 (552, 2016, 'Bangalore', '2016-05-07'): Int64Index([551], dtype='int64'),
 (553, 2016, 'Chandigarh', '2016-05-07'): Int64Index([552], dtype='int64'),
 (554, 2016, 'Visakhapatnam', '2016-05-08'): Int64Index([553], dtype='int64'),
 (555, 2016, 'Kolkata', '2016-05-08'): Int64Index([554], dtype='int64'),
 (556, 2016, 'Chandigarh', '2016-05-09'): Int64Index([555], dtype='int64'),
 (557, 2016, 'Visakhapatnam', '2016-05-10'): Int64Index([556], dtype='int64'),
 (558, 2016, 'Bangalore', '2016-05-11'): Int64Index([557], dtype='int64'),
 (559, 2016, 'Hyderabad', '2016-05-12'): Int64Index([558], dtype='int64'),
 (560, 2016, 'Visakhapatnam', '2016-05-13'): Int64Index([559], dtype='int64'),
 (561, 2016, 'Bangalore', '2016-05-14'): Int64Index([560], dtype='int64'),
 (562, 2016, 'Kolkata', '2016-05-14'): Int64Index([561], dtype='int64'),
 (563, 2016, 'Chandigarh', '2016-05-15'): Int64Index([562], dtype='int64'),
 (564, 2016, 'Visakhapatnam', '2016-05-15'): Int64Index([563], dtype='int64'),
 (565, 2016, 'Kolkata', '2016-05-16'): Int64Index([564], dtype='int64'),
 (566, 2016, 'Visakhapatnam', '2016-05-17'): Int64Index([565], dtype='int64'),
 (567, 2016, 'Bangalore', '2016-05-18'): Int64Index([566], dtype='int64')}

In [50]:
# 3. The final match of the season 2011 is at the index 247, on what date was the match played?
a=matches[247:248]
a.groupby('date').groups

{'2011-05-28': Int64Index([247], dtype='int64')}

In [64]:
# 4. Create a new dataframe called matches_compact which contains only the id, season, date and winner. 
#What is the shape of the matches_compact?
matches_compact=pd.DataFrame(matches,columns=(['id','season','date','winner']))
matches_compact
matches_compact.shape

(577, 4)

In [114]:
# 5. How many matches were played in the year 2010? 
matches.groupby('season').sum()

           id  dl_applied  win_by_runs  win_by_wickets  umpire3
season
2008     1711           2          705             221      0.0
2009     4959           3          764             180      0.0
2010     8730           0          976             190      0.0
2011    15476           3         1098             265      0.0
2012    21127           0          960             241      0.0
2013    27398           0         1241             227      0.0
2014    25710           1          644             225      0.0
2015    28792           2          850             148      0.0
2016    32850           4          676             244      0.0

In [112]:
# 6. How will you find the highest margin of runs by which any team won the match in matches so far? 
#Which team was it and by how many runs did it win?
a=matches.groupby(['winner']).win_by_runs.max()
print(a)

winner
Chennai Super Kings             97
Deccan Chargers                 82
Delhi Daredevils                67
Gujarat Lions                    1
Kings XI Punjab                111
Kochi Tuskers Kerala            17
Kolkata Knight Riders          140
Mumbai Indians                  98
Pune Warriors                   38
Rajasthan Royals               105
Rising Pune Supergiants         34
Royal Challengers Bangalore    144
Sunrisers Hyderabad             85
Name: win_by_runs, dtype: int64

In [307]:
# 7. Here is a dictionary of short names for all the team names in the dataset. Create a new dataframe called 
# matches_alias by replacing names in all the columns with long team names.
team_names = {'Kolkata Knight Riders': 'KKR', 
              'Chennai Super Kings': 'CSK', 
              'Rajasthan Royals' : 'RR',
               'Mumbai Indians' : 'MI', 
              'Deccan Chargers' : 'DC', 
              'Kings XI Punjab' : 'KIXP',
               'Royal Challengers Bangalore' : 'RCB', 
              'Delhi Daredevils' : 'DD',
              'Kochi Tuskers Kerala' : 'KTK', 
              'Pune Warriors' : 'PW', 
              'Sunrisers Hyderabad' : 'SRH',
              'Rising Pune Supergiants' : 'RPS', 
              'Gujarat Lions' : 'GL'}

team_names
matches_alias=pd.DataFrame([team_names])
matches_alias.replace('csk','chennai super kings')
matches_alias

,Chennai Super Kings,Deccan Chargers,Delhi Daredevils,Gujarat Lions,Kings XI Punjab,Kochi Tuskers Kerala,Kolkata Knight Riders,Mumbai Indians,Pune Warriors,Rajasthan Royals,Rising Pune Supergiants,Royal Challengers Bangalore,Sunrisers Hyderabad
0,CSK,DC,DD,GL,KIXP,KTK,KKR,MI,PW,RR,RPS,RCB,SRH

In [270]:
# 8. Find out in which stadium the maximum number of matches have been played and in which stadium minimum? 
# What is the highest and the lowest number? Show the code.
x=matches.venue.value_counts()
x

M Chinnaswamy Stadium                                   58
Eden Gardens                                            54
Feroz Shah Kotla                                        53
Wankhede Stadium                                        49
MA Chidambaram Stadium, Chepauk                         48
Rajiv Gandhi International Stadium, Uppal               41
Punjab Cricket Association Stadium, Mohali              35
Sawai Mansingh Stadium                                  33
Subrata Roy Sahara Stadium                              17
Dr DY Patil Sports Academy                              17
Kingsmead                                               15
SuperSport Park                                         12
Sardar Patel Stadium, Motera                            12
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     11
Brabourne Stadium                                       11
Himachal Pradesh Cricket Association Stadium             9
Maharashtra Cricket Association Stadium                  8
New Wanderers Stadium                                    8
Dubai International Cricket Stadium                      7
St George's Park                                         7
Sheikh Zayed Stadium                                     7
Barabati Stadium                                         7
JSCA International Stadium Complex                       7
Punjab Cricket Association IS Bindra Stadium, Mohali     7
Newlands                                                 7
Shaheed Veer Narayan Singh International Stadium         6
Sharjah Cricket Stadium                                  6
Saurashtra Cricket Association Stadium                   5
Nehru Stadium                                            5
Vidarbha Cricket Association Stadium, Jamtha             3
De Beers Diamond Oval                                    3
Buffalo Park                                             3
Green Park                                               2
Holkar Cricket Stadium                                   2
OUTsurance Oval                                          2
Name: venue, dtype: int64

In [153]:
# 9. The following dataframe contains large blocks of NaNs. 
# Fill the NAs with mean only for 2 or less consecutive values of NAs. 
# Refer to the documentation of fillna() to find out the parameter you would use to fill only a certail number of NAs.
# The resulting dataframe should look like df_filled shown below.

df = pd.DataFrame({'val1':[4,np.nan,7,np.nan,np.nan,9,5, np.nan , 1,9,np.nan, np.nan,np.nan, 5, np.nan], 
                    'val2': [ np.nan, 5,7,np.nan, np.nan,8,3,np.nan, 4,np.nan, np.nan, np.nan,np.nan,21,np.nan]})

d = {'val1': {0: 4.0,1: 5.7142857142857144,2: 7.0,3: 5.7142857142857144,4: np.nan,5: 9.0,6: 5.0,7: np.nan,8: 1.0,9: 9.0,10: np.nan,11: np.nan,12: np.nan,13: 5.0,14: np.nan},
'val2': {0: 8.0,1: 5.0,2: 7.0,3: 8.0,4: np.nan,5: 8.0,6: 3.0,7: np.nan,8: 4.0,9: np.nan,10: np.nan,11: np.nan,12: np.nan,13: 21.0,14: np.nan}}

df_filled = pd.DataFrame(d)

In [253]:
df = pd.DataFrame({'val1':[4,np.nan,7,np.nan,np.nan,9,5, np.nan , 1,9,np.nan, np.nan,np.nan, 5, np.nan], 
                    'val2': [ np.nan, 5,7,np.nan, np.nan,8,3,np.nan, 4,np.nan, np.nan, np.nan,np.nan,21,np.nan]})
c=df.mean()
c
df.fillna(c,limit=2)

        val1  val2
0   4.000000   8.0
1   5.714286   5.0
2   7.000000   7.0
3   5.714286   8.0
4        NaN   NaN
5   9.000000   8.0
6   5.000000   3.0
7        NaN   NaN
8   1.000000   4.0
9   9.000000   NaN
10       NaN   NaN
11       NaN   NaN
12       NaN   NaN
13  5.000000  21.0
14       NaN   NaN

In [4]:
# 10. For the dataframe given below, 
# Convert the NaN values to zero
# Add a row called diff with the difference between minimum and maximum value in each column. Try solving it using lambda function
# Add a column called diff with the difference between minimum and maximum value in each row. 
# The final df should look like df_final shown below

df = pd.DataFrame({'val1':[9,15,71,9,5], 'val2': [8,31,10, 14,np.nan]})

df_final = pd.DataFrame({'diff': {0: 1.0, 1: 16.0, 2: 61.0, 3: 5.0, 4: 5.0, 'diff': 35.0},
 'val1': {0: 9.0, 1: 15.0, 2: 71.0, 3: 9.0, 4: 5.0, 'diff': 66.0},
 'val2': {0: 8.0, 1: 31.0, 2: 10.0, 3: 14.0, 4: 0.0, 'diff': 31.0}})

df_final

      diff  val1  val2
0      1.0   9.0   8.0
1     16.0  15.0  31.0
2     61.0  71.0  10.0
3      5.0   9.0  14.0
4      5.0   5.0   0.0
diff  35.0  66.0  31.0

In [343]:
a=pd.DataFrame({'val1':[9,15,71,9,np.nan], 'val2': [8,31,10, 14,np.nan]})

a.loc['diff']=a.max()-a.min()
a['diff']=(a['val1']-a['val2'])
a.fillna(0)

      val1  val2  diff
0      9.0   8.0   1.0
1     15.0  31.0 -16.0
2     71.0  10.0  61.0
3      9.0  14.0  -5.0
4      0.0   0.0   0.0
diff  62.0  23.0  39.0